name: Push
run-name: Push ${{ github.ref_name }}
on: [push]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{github.ref_name}}

      - run: echo "Pull Request ${number} is ${state} (${sha})"
        if: ${{ steps.find-pull-request.outputs.state != 'open' }}
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}
          state: ${{ steps.find-pull-request.outputs.state }}
  step2:
    runs-on: ubuntu-latest
    needs: base
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{needs.base.result}}
