name: Push
run-name: Push ${{ github.ref_name }}
on: [push]

permissions:
  actions: write

jobs:
  base:
    runs-on: ubuntu-latest
    outputs:
      has-pr: ${{ steps.state-of-pr.outputs.state }}
    steps:
      - uses: actions/checkout@v4
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: ${{github.ref_name}}
      - name: State of PR
        id: state-of-pr
        run: echo "state=${{ steps.find-pull-request.outputs.state == 'open' }}" >> "$GITHUB_OUTPUT"
      - run: echo "Pull Request ${number} is ${state} (${sha})"
        if: ${{ steps.find-pull-request.outputs.state != 'open' }}
        env:
          number: ${{ steps.find-pull-request.outputs.number }}
          sha: ${{ steps.find-pull-request.outputs.head-sha }}
          state: ${{ steps.find-pull-request.outputs.state }}
  step2:
    runs-on: ubuntu-latest
    needs: base
    if: ${{ needs.base.outputs.has-pr != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{needs.base.result}}
  # clean:
  #   runs-on: ubuntu-latest
  #   needs: base
  #   if: always()
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Clear cache
  #       uses: actions/github-script@v6
  #       with:
  #         script: |
  #           const script = require('./.github/actions/clean-cache.js')
  #           script({github, context})
