name: Verify build
run-name: Verify build

on:
  workflow_call:

jobs:
  base:
    name: Verify build
    runs-on: ubuntu-latest
    steps:
      - name: ✨ Checkout
        uses: actions/checkout@v4
      - name: 🧶 Install Yarn
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: 📦 Cache Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Restore Build
        id: cache-build-restore
        uses: actions/cache/restore@v3
        with:
          path: .next/
          key: build-${{ runner.os }}
      - name: Build not found
        if: steps.cache-build-restore.outputs.cache-hit != 'true'
        run: echo build not found
      - name: Build found
        if: steps.cache-build-restore.outputs.cache-hit == 'true'
        run: ls -la .next/
